version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/app/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/web-nginx/"
    schedule:
      interval: "weekly"

